language: node_js 
node_js:
  - 11.9
env:
  - NODE_ENV='test'
before_install: 
  - cd ui
  - yarn
  - cd ../server
  - yarn
  - cd ..
cache:
  yarn: true
jobs:
  include:
    - stage: ui testing
      script: cd ui 
        && yarn test
        && yarn lint:js
        && yarn lint:css
    - stage: server testing
      script: cd server
        && yarn lint:js
    - stage: ui build
      script: cd ui 
        && yarn build
    - stage: server build
      script: cd server
        && yarn build