language: node_js 
node_js:
  - 11.9
env:
  - NODE_ENV='test'
before_install: 
  - cd ui
  - yarn
  - cd ../server
  - yarn
  - cd ..
cache:
  yarn: true
script: cd ui 
  && yarn test
  && yarn lint:js
  && yarn lint:css
  && cd ..
  && yarn test
  && yarn lint:js
