type AbuseIP {
    ipAddress: String,
    isPublic: Boolean,
    ipVersion: Int,
    isWhitelisted: Boolean,
    abuseConfidenceScore: Int
    usageType: String,
    domain: String
}

extend type Query {
    abuseIP(ip: String!): AbuseIP
}
